---
- name: Update Proxmox Cluster with HA Maintenance
  hosts: proxmox_cluster_prod
  become: yes
  gather_facts: yes
  serial: 1  # Process one node at a time for stability in the cluster

  tasks:
    - name: Put node in maintenance mode using ha-manager
      shell: ha-manager crm-command node-maintenance disable "{{ inventory_hostname }}"
      register: maintenance_mode
      changed_when: false

    - name: Confirm node is in maintenance mode
      shell: ha-manager status | grep "{{ inventory_hostname }}"
      register: ha_status
      changed_when: false
      until: "'maintenance' in ha_status.stdout"
      retries: 10
      delay: 15

    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if needed
      reboot:
        msg: "Rebooting to apply updates"
        connect_timeout: 5
        reboot_timeout: 600
      when: reboot_required.stat.exists

    - name: Wait for node to come back online
      wait_for_connection:
        delay: 10
        timeout: 300
      when: reboot_required.stat.exists

    - name: Verify Proxmox services are running
      shell: systemctl is-active pve-cluster
      register: proxmox_status
      changed_when: false

    - name: Check Proxmox status
      debug:
        msg: "Proxmox services are running correctly."
      when: proxmox_status.stdout == "active"

    - name: Remove node from maintenance mode using ha-manager
      shell: ha-manager node-maintenance --disable
      when: maintenance_mode is succeeded
      changed_when: false
